/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AturSandiRouteImport } from './routes/atur-sandi'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KabarRouteImport } from './routes/kabar'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as LengkapiProfilRouteImport } from './routes/lengkapi-profil'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as PanduanPasangRouteImport } from './routes/panduan-pasang'
import { Route as PenjualRouteImport } from './routes/penjual'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SimulatorBayarRouteImport } from './routes/simulator-bayar'
import { Route as TimRouteImport } from './routes/tim'
import { Route as BayarOrderIdRouteImport } from './routes/bayar.$orderId'
import { Route as PenjualIndexRouteImport } from './routes/penjual.index'
import { Route as PenjualDaftarRouteImport } from './routes/penjual.daftar'
import { Route as PenjualDapurRouteImport } from './routes/penjual.dapur'
import { Route as PenjualMenuRouteImport } from './routes/penjual.menu'
import { Route as PenjualSetoranRouteImport } from './routes/penjual.setoran'
import { Route as PenjualTokoRouteImport } from './routes/penjual.toko'
import { Route as PesananIndexRouteImport } from './routes/pesanan.index'
import { Route as PesananOrderIdRouteImport } from './routes/pesanan.$orderId'
import { Route as StrukOrderIdRouteImport } from './routes/struk.$orderId'
import { Route as TenantSlugRouteImport } from './routes/tenant.$slug'
import { Route as TimIndexRouteImport } from './routes/tim.index'
import { Route as TimAnggotaRouteImport } from './routes/tim.anggota'
import { Route as TimLaporanRouteImport } from './routes/tim.laporan'
import { Route as TimPenjualRouteImport } from './routes/tim.penjual'
import { Route as TimSetoranRouteImport } from './routes/tim.setoran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AturSandiRoute = AturSandiRouteImport.update({
  id: '/atur-sandi',
  path: '/atur-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KabarRoute = KabarRouteImport.update({
  id: '/kabar',
  path: '/kabar',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const LengkapiProfilRoute = LengkapiProfilRouteImport.update({
  id: '/lengkapi-profil',
  path: '/lengkapi-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanPasangRoute = PanduanPasangRouteImport.update({
  id: '/panduan-pasang',
  path: '/panduan-pasang',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualRoute = PenjualRouteImport.update({
  id: '/penjual',
  path: '/penjual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorBayarRoute = SimulatorBayarRouteImport.update({
  id: '/simulator-bayar',
  path: '/simulator-bayar',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const BayarOrderIdRoute = BayarOrderIdRouteImport.update({
  id: '/bayar/$orderId',
  path: '/bayar/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualIndexRoute = PenjualIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PenjualRoute,
} as any)
const PenjualDaftarRoute = PenjualDaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => PenjualRoute,
} as any)
const PenjualDapurRoute = PenjualDapurRouteImport.update({
  id: '/dapur',
  path: '/dapur',
  getParentRoute: () => PenjualRoute,
} as any)
const PenjualMenuRoute = PenjualMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PenjualRoute,
} as any)
const PenjualSetoranRoute = PenjualSetoranRouteImport.update({
  id: '/setoran',
  path: '/setoran',
  getParentRoute: () => PenjualRoute,
} as any)
const PenjualTokoRoute = PenjualTokoRouteImport.update({
  id: '/toko',
  path: '/toko',
  getParentRoute: () => PenjualRoute,
} as any)
const PesananIndexRoute = PesananIndexRouteImport.update({
  id: '/pesanan/',
  path: '/pesanan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananOrderIdRoute = PesananOrderIdRouteImport.update({
  id: '/pesanan/$orderId',
  path: '/pesanan/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const StrukOrderIdRoute = StrukOrderIdRouteImport.update({
  id: '/struk/$orderId',
  path: '/struk/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugRoute = TenantSlugRouteImport.update({
  id: '/tenant/$slug',
  path: '/tenant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TimIndexRoute = TimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimRoute,
} as any)
const TimAnggotaRoute = TimAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => TimRoute,
} as any)
const TimLaporanRoute = TimLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => TimRoute,
} as any)
const TimPenjualRoute = TimPenjualRouteImport.update({
  id: '/penjual',
  path: '/penjual',
  getParentRoute: () => TimRoute,
} as any)
const TimSetoranRoute = TimSetoranRouteImport.update({
  id: '/setoran',
  path: '/setoran',
  getParentRoute: () => TimRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atur-sandi': typeof AturSandiRoute
  '/checkout': typeof CheckoutRoute
  '/kabar': typeof KabarRoute
  '/keranjang': typeof KeranjangRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
  '/masuk': typeof MasukRoute
  '/panduan-pasang': typeof PanduanPasangRoute
  '/penjual': typeof PenjualRouteWithChildren
  '/profil': typeof ProfilRoute
  '/simulator-bayar': typeof SimulatorBayarRoute
  '/tim': typeof TimRouteWithChildren
  '/bayar/$orderId': typeof BayarOrderIdRoute
  '/penjual/daftar': typeof PenjualDaftarRoute
  '/penjual/dapur': typeof PenjualDapurRoute
  '/penjual/menu': typeof PenjualMenuRoute
  '/penjual/setoran': typeof PenjualSetoranRoute
  '/penjual/toko': typeof PenjualTokoRoute
  '/pesanan/$orderId': typeof PesananOrderIdRoute
  '/struk/$orderId': typeof StrukOrderIdRoute
  '/tenant/$slug': typeof TenantSlugRoute
  '/tim/anggota': typeof TimAnggotaRoute
  '/tim/laporan': typeof TimLaporanRoute
  '/tim/penjual': typeof TimPenjualRoute
  '/tim/setoran': typeof TimSetoranRoute
  '/penjual/': typeof PenjualIndexRoute
  '/pesanan/': typeof PesananIndexRoute
  '/tim/': typeof TimIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atur-sandi': typeof AturSandiRoute
  '/checkout': typeof CheckoutRoute
  '/kabar': typeof KabarRoute
  '/keranjang': typeof KeranjangRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
  '/masuk': typeof MasukRoute
  '/panduan-pasang': typeof PanduanPasangRoute
  '/profil': typeof ProfilRoute
  '/simulator-bayar': typeof SimulatorBayarRoute
  '/bayar/$orderId': typeof BayarOrderIdRoute
  '/penjual/daftar': typeof PenjualDaftarRoute
  '/penjual/dapur': typeof PenjualDapurRoute
  '/penjual/menu': typeof PenjualMenuRoute
  '/penjual/setoran': typeof PenjualSetoranRoute
  '/penjual/toko': typeof PenjualTokoRoute
  '/pesanan/$orderId': typeof PesananOrderIdRoute
  '/struk/$orderId': typeof StrukOrderIdRoute
  '/tenant/$slug': typeof TenantSlugRoute
  '/tim/anggota': typeof TimAnggotaRoute
  '/tim/laporan': typeof TimLaporanRoute
  '/tim/penjual': typeof TimPenjualRoute
  '/tim/setoran': typeof TimSetoranRoute
  '/penjual': typeof PenjualIndexRoute
  '/pesanan': typeof PesananIndexRoute
  '/tim': typeof TimIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atur-sandi': typeof AturSandiRoute
  '/checkout': typeof CheckoutRoute
  '/kabar': typeof KabarRoute
  '/keranjang': typeof KeranjangRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
  '/masuk': typeof MasukRoute
  '/panduan-pasang': typeof PanduanPasangRoute
  '/penjual': typeof PenjualRouteWithChildren
  '/profil': typeof ProfilRoute
  '/simulator-bayar': typeof SimulatorBayarRoute
  '/tim': typeof TimRouteWithChildren
  '/bayar/$orderId': typeof BayarOrderIdRoute
  '/penjual/daftar': typeof PenjualDaftarRoute
  '/penjual/dapur': typeof PenjualDapurRoute
  '/penjual/menu': typeof PenjualMenuRoute
  '/penjual/setoran': typeof PenjualSetoranRoute
  '/penjual/toko': typeof PenjualTokoRoute
  '/pesanan/$orderId': typeof PesananOrderIdRoute
  '/struk/$orderId': typeof StrukOrderIdRoute
  '/tenant/$slug': typeof TenantSlugRoute
  '/tim/anggota': typeof TimAnggotaRoute
  '/tim/laporan': typeof TimLaporanRoute
  '/tim/penjual': typeof TimPenjualRoute
  '/tim/setoran': typeof TimSetoranRoute
  '/penjual/': typeof PenjualIndexRoute
  '/pesanan/': typeof PesananIndexRoute
  '/tim/': typeof TimIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atur-sandi'
    | '/checkout'
    | '/kabar'
    | '/keranjang'
    | '/lengkapi-profil'
    | '/masuk'
    | '/panduan-pasang'
    | '/penjual'
    | '/profil'
    | '/simulator-bayar'
    | '/tim'
    | '/bayar/$orderId'
    | '/penjual/daftar'
    | '/penjual/dapur'
    | '/penjual/menu'
    | '/penjual/setoran'
    | '/penjual/toko'
    | '/pesanan/$orderId'
    | '/struk/$orderId'
    | '/tenant/$slug'
    | '/tim/anggota'
    | '/tim/laporan'
    | '/tim/penjual'
    | '/tim/setoran'
    | '/penjual/'
    | '/pesanan/'
    | '/tim/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atur-sandi'
    | '/checkout'
    | '/kabar'
    | '/keranjang'
    | '/lengkapi-profil'
    | '/masuk'
    | '/panduan-pasang'
    | '/profil'
    | '/simulator-bayar'
    | '/bayar/$orderId'
    | '/penjual/daftar'
    | '/penjual/dapur'
    | '/penjual/menu'
    | '/penjual/setoran'
    | '/penjual/toko'
    | '/pesanan/$orderId'
    | '/struk/$orderId'
    | '/tenant/$slug'
    | '/tim/anggota'
    | '/tim/laporan'
    | '/tim/penjual'
    | '/tim/setoran'
    | '/penjual'
    | '/pesanan'
    | '/tim'
  id:
    | '__root__'
    | '/'
    | '/atur-sandi'
    | '/checkout'
    | '/kabar'
    | '/keranjang'
    | '/lengkapi-profil'
    | '/masuk'
    | '/panduan-pasang'
    | '/penjual'
    | '/profil'
    | '/simulator-bayar'
    | '/tim'
    | '/bayar/$orderId'
    | '/penjual/daftar'
    | '/penjual/dapur'
    | '/penjual/menu'
    | '/penjual/setoran'
    | '/penjual/toko'
    | '/pesanan/$orderId'
    | '/struk/$orderId'
    | '/tenant/$slug'
    | '/tim/anggota'
    | '/tim/laporan'
    | '/tim/penjual'
    | '/tim/setoran'
    | '/penjual/'
    | '/pesanan/'
    | '/tim/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AturSandiRoute: typeof AturSandiRoute
  CheckoutRoute: typeof CheckoutRoute
  KabarRoute: typeof KabarRoute
  KeranjangRoute: typeof KeranjangRoute
  LengkapiProfilRoute: typeof LengkapiProfilRoute
  MasukRoute: typeof MasukRoute
  PanduanPasangRoute: typeof PanduanPasangRoute
  PenjualRoute: typeof PenjualRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  SimulatorBayarRoute: typeof SimulatorBayarRoute
  TimRoute: typeof TimRouteWithChildren
  BayarOrderIdRoute: typeof BayarOrderIdRoute
  PesananOrderIdRoute: typeof PesananOrderIdRoute
  StrukOrderIdRoute: typeof StrukOrderIdRoute
  TenantSlugRoute: typeof TenantSlugRoute
  PesananIndexRoute: typeof PesananIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atur-sandi': {
      id: '/atur-sandi'
      path: '/atur-sandi'
      fullPath: '/atur-sandi'
      preLoaderRoute: typeof AturSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabar': {
      id: '/kabar'
      path: '/kabar'
      fullPath: '/kabar'
      preLoaderRoute: typeof KabarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lengkapi-profil': {
      id: '/lengkapi-profil'
      path: '/lengkapi-profil'
      fullPath: '/lengkapi-profil'
      preLoaderRoute: typeof LengkapiProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan-pasang': {
      id: '/panduan-pasang'
      path: '/panduan-pasang'
      fullPath: '/panduan-pasang'
      preLoaderRoute: typeof PanduanPasangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjual': {
      id: '/penjual'
      path: '/penjual'
      fullPath: '/penjual'
      preLoaderRoute: typeof PenjualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator-bayar': {
      id: '/simulator-bayar'
      path: '/simulator-bayar'
      fullPath: '/simulator-bayar'
      preLoaderRoute: typeof SimulatorBayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bayar/$orderId': {
      id: '/bayar/$orderId'
      path: '/bayar/$orderId'
      fullPath: '/bayar/$orderId'
      preLoaderRoute: typeof BayarOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjual/': {
      id: '/penjual/'
      path: '/'
      fullPath: '/penjual/'
      preLoaderRoute: typeof PenjualIndexRouteImport
      parentRoute: typeof PenjualRoute
    }
    '/penjual/daftar': {
      id: '/penjual/daftar'
      path: '/daftar'
      fullPath: '/penjual/daftar'
      preLoaderRoute: typeof PenjualDaftarRouteImport
      parentRoute: typeof PenjualRoute
    }
    '/penjual/dapur': {
      id: '/penjual/dapur'
      path: '/dapur'
      fullPath: '/penjual/dapur'
      preLoaderRoute: typeof PenjualDapurRouteImport
      parentRoute: typeof PenjualRoute
    }
    '/penjual/menu': {
      id: '/penjual/menu'
      path: '/menu'
      fullPath: '/penjual/menu'
      preLoaderRoute: typeof PenjualMenuRouteImport
      parentRoute: typeof PenjualRoute
    }
    '/penjual/setoran': {
      id: '/penjual/setoran'
      path: '/setoran'
      fullPath: '/penjual/setoran'
      preLoaderRoute: typeof PenjualSetoranRouteImport
      parentRoute: typeof PenjualRoute
    }
    '/penjual/toko': {
      id: '/penjual/toko'
      path: '/toko'
      fullPath: '/penjual/toko'
      preLoaderRoute: typeof PenjualTokoRouteImport
      parentRoute: typeof PenjualRoute
    }
    '/pesanan/': {
      id: '/pesanan/'
      path: '/pesanan'
      fullPath: '/pesanan/'
      preLoaderRoute: typeof PesananIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/$orderId': {
      id: '/pesanan/$orderId'
      path: '/pesanan/$orderId'
      fullPath: '/pesanan/$orderId'
      preLoaderRoute: typeof PesananOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/struk/$orderId': {
      id: '/struk/$orderId'
      path: '/struk/$orderId'
      fullPath: '/struk/$orderId'
      preLoaderRoute: typeof StrukOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$slug': {
      id: '/tenant/$slug'
      path: '/tenant/$slug'
      fullPath: '/tenant/$slug'
      preLoaderRoute: typeof TenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim/': {
      id: '/tim/'
      path: '/'
      fullPath: '/tim/'
      preLoaderRoute: typeof TimIndexRouteImport
      parentRoute: typeof TimRoute
    }
    '/tim/anggota': {
      id: '/tim/anggota'
      path: '/anggota'
      fullPath: '/tim/anggota'
      preLoaderRoute: typeof TimAnggotaRouteImport
      parentRoute: typeof TimRoute
    }
    '/tim/laporan': {
      id: '/tim/laporan'
      path: '/laporan'
      fullPath: '/tim/laporan'
      preLoaderRoute: typeof TimLaporanRouteImport
      parentRoute: typeof TimRoute
    }
    '/tim/penjual': {
      id: '/tim/penjual'
      path: '/penjual'
      fullPath: '/tim/penjual'
      preLoaderRoute: typeof TimPenjualRouteImport
      parentRoute: typeof TimRoute
    }
    '/tim/setoran': {
      id: '/tim/setoran'
      path: '/setoran'
      fullPath: '/tim/setoran'
      preLoaderRoute: typeof TimSetoranRouteImport
      parentRoute: typeof TimRoute
    }
  }
}

interface PenjualRouteChildren {
  PenjualDaftarRoute: typeof PenjualDaftarRoute
  PenjualDapurRoute: typeof PenjualDapurRoute
  PenjualMenuRoute: typeof PenjualMenuRoute
  PenjualSetoranRoute: typeof PenjualSetoranRoute
  PenjualTokoRoute: typeof PenjualTokoRoute
  PenjualIndexRoute: typeof PenjualIndexRoute
}

const PenjualRouteChildren: PenjualRouteChildren = {
  PenjualDaftarRoute: PenjualDaftarRoute,
  PenjualDapurRoute: PenjualDapurRoute,
  PenjualMenuRoute: PenjualMenuRoute,
  PenjualSetoranRoute: PenjualSetoranRoute,
  PenjualTokoRoute: PenjualTokoRoute,
  PenjualIndexRoute: PenjualIndexRoute,
}

const PenjualRouteWithChildren =
  PenjualRoute._addFileChildren(PenjualRouteChildren)

interface TimRouteChildren {
  TimAnggotaRoute: typeof TimAnggotaRoute
  TimLaporanRoute: typeof TimLaporanRoute
  TimPenjualRoute: typeof TimPenjualRoute
  TimSetoranRoute: typeof TimSetoranRoute
  TimIndexRoute: typeof TimIndexRoute
}

const TimRouteChildren: TimRouteChildren = {
  TimAnggotaRoute: TimAnggotaRoute,
  TimLaporanRoute: TimLaporanRoute,
  TimPenjualRoute: TimPenjualRoute,
  TimSetoranRoute: TimSetoranRoute,
  TimIndexRoute: TimIndexRoute,
}

const TimRouteWithChildren = TimRoute._addFileChildren(TimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AturSandiRoute: AturSandiRoute,
  CheckoutRoute: CheckoutRoute,
  KabarRoute: KabarRoute,
  KeranjangRoute: KeranjangRoute,
  LengkapiProfilRoute: LengkapiProfilRoute,
  MasukRoute: MasukRoute,
  PanduanPasangRoute: PanduanPasangRoute,
  PenjualRoute: PenjualRouteWithChildren,
  ProfilRoute: ProfilRoute,
  SimulatorBayarRoute: SimulatorBayarRoute,
  TimRoute: TimRouteWithChildren,
  BayarOrderIdRoute: BayarOrderIdRoute,
  PesananOrderIdRoute: PesananOrderIdRoute,
  StrukOrderIdRoute: StrukOrderIdRoute,
  TenantSlugRoute: TenantSlugRoute,
  PesananIndexRoute: PesananIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
